package com.quizverse.app.util

import java.time.LocalDate

/**
 * 365 daily motivational quotes for the QuizVerse home screen.
 * One unique quote per day of the year, cycling annually.
 */
object DailyQuotes {

    fun randomQuote(exclude: String? = null): String {
        if (exclude == null) return quotes.random()
        var next: String
        do { next = quotes.random() } while (next == exclude)
        return next
    }

    private val quotes = listOf(
        // --- Januar (1-31) ---
        "Wissen ist die einzige Ressource, die sich vermehrt, wenn man sie teilt.",
        "Jede Frage, die du beantwortest, macht dich klüger.",
        "Der Weg zum Wissen beginnt mit einer einzigen Frage.",
        "Neugier ist der Schlüssel zu allem Wissen.",
        "Heute ist ein guter Tag, um etwas Neues zu lernen!",
        "Wer fragt, bleibt nicht dumm.",
        "Dein Gehirn liebt Herausforderungen \u2014 gib ihm eine!",
        "Jedes Quiz bringt dich einen Schritt weiter.",
        "Bildung ist die mächtigste Waffe der Welt.",
        "Lerne, als würdest du ewig leben.",
        "Wissen ist wie ein Muskel \u2014 trainiere ihn täglich!",
        "Die besten Ideen kommen aus neugierigen Köpfen.",
        "Ein Tag ohne Lernen ist ein verlorener Tag.",
        "Stelle dich der Herausforderung \u2014 du kannst mehr als du denkst!",
        "Wissen macht nicht nur klug, sondern auch mutig.",
        "Fehler sind die besten Lehrer \u2014 trau dich!",
        "Jede richtige Antwort ist ein kleiner Sieg.",
        "Dein Wissen von heute formt dein Morgen.",
        "Lernen ist ein Abenteuer \u2014 genieße die Reise!",
        "Je mehr du weißt, desto mehr siehst du.",
        "Wissen öffnet Türen, die du noch gar nicht kennst.",
        "Sei neugierig, sei mutig, sei schlau!",
        "Heute Abend weißt du mehr als heute Morgen.",
        "Ein kluger Kopf hat nie genug Fragen.",
        "Wer aufhört zu lernen, hört auf zu wachsen.",
        "Du bist nur ein Quiz entfernt von neuem Wissen!",
        "Mach jeden Tag zu deinem Lerntag.",
        "Die Welt gehört den Neugierigen.",
        "Starte jetzt \u2014 dein Gehirn wartet schon!",
        "Wissen sammeln macht süchtig \u2014 im besten Sinne!",
        "Jede Frage ist eine Chance, etwas zu entdecken.",

        // --- Februar (32-59) ---
        "Denken ist die schwerste Arbeit \u2014 deshalb tun es so wenige.",
        "Wer neugierig bleibt, bleibt jung im Kopf.",
        "Ein Quiz am Tag hält die Langeweile fern.",
        "Wissen ist Macht \u2014 nutze sie weise!",
        "Der kluge Mensch lernt aus allem und von jedem.",
        "Dein Potenzial ist grenzenlos \u2014 entdecke es!",
        "Jede Antwort führt zu einer neuen Frage.",
        "Das Gehirn ist der beste Computer \u2014 update es regelmäßig!",
        "Wissen wächst, wenn du es teilst.",
        "Heute schon etwas Neues gelernt? Los geht's!",
        "Intelligenz ist nicht das Wissen selbst, sondern die Vorstellungskraft.",
        "Wer liest, reist \u2014 auch ohne sich zu bewegen.",
        "Jedes Wissensgebiet hat seine eigene Schönheit.",
        "Habe Mut, deinen eigenen Verstand zu gebrauchen!",
        "Lernen ist keine Pflicht, sondern ein Geschenk.",
        "Der Anfang ist die Hälfte des Ganzen.",
        "Manche Antworten findest du nur, wenn du fragst.",
        "Wissen verbindet Menschen über alle Grenzen hinweg.",
        "Dein nächster Aha-Moment wartet schon!",
        "Wer nichts weiß, muss alles glauben.",
        "Bildung ist der Reisepass in die Zukunft.",
        "Jede Stunde Lernen ist eine Investition in dich selbst.",
        "Das Schöne am Lernen: Es hört nie auf.",
        "Teste dein Wissen \u2014 überrasche dich selbst!",
        "Ein neugieriger Geist ist ein reicher Geist.",
        "Wissen ist der Kompass auf deiner Lebensreise.",
        "Nicht das Wissen allein, sondern das Anwenden zählt.",
        "Heute ist der perfekte Tag für ein Quiz!",

        // --- Maerz (60-90) ---
        "Lernen ist wie Rudern gegen den Strom \u2014 wer aufhört, treibt zurück.",
        "Dein Wissen ist dein größter Schatz.",
        "Jede neue Information ist ein Puzzleteil deines Weltbildes.",
        "Gib niemals auf zu lernen \u2014 das Leben gibt nie auf zu lehren.",
        "Wissen schafft Vertrauen, Vertrauen schafft Erfolg.",
        "Die Investition in Wissen zahlt die besten Zinsen.",
        "Ein Buch, ein Quiz, eine neue Erkenntnis \u2014 jeden Tag!",
        "Wer viel fragt, bekommt viele Antworten.",
        "Dein Verstand kennt keine Grenzen \u2014 challenge ihn!",
        "Wissen ist die Brücke zwischen Träumen und Wirklichkeit.",
        "Jeder Experte war einmal ein Anfänger.",
        "Lernen macht glücklich \u2014 das ist wissenschaftlich bewiesen!",
        "Das Beste, was du heute tun kannst: etwas Neues lernen.",
        "Wissen ist wie Licht \u2014 es vertreibt die Dunkelheit.",
        "Bleib hungrig nach Wissen, bleib bescheiden im Erfolg.",
        "Dein Gehirn dankt es dir \u2014 gib ihm Futter!",
        "Kleine Schritte führen zu großen Erkenntnissen.",
        "Die Neugier hat ihren eigenen Grund zu existieren.",
        "Wissen ist keine Last, sondern Flügel.",
        "Jede Minute Lernen ist eine Minute gut investiert.",
        "Denke gross, lerne täglich, wachse stetig!",
        "Die klügsten Menschen stellen die einfachsten Fragen.",
        "Heute ein Quiz, morgen ein Gesprächsthema mehr!",
        "Wissen ist der Samen, Anwendung die Ernte.",
        "Nicht die Antwort zählt, sondern der Weg dahin.",
        "Dein Wissensvorsprung beginnt mit dem ersten Klick.",
        "Lernen ist die Superkraft, die jeder hat.",
        "Lass dich inspirieren \u2014 von Fragen und Antworten!",
        "Wer lernt, verändert die Welt \u2014 angefangen bei sich selbst.",
        "Jeden Tag ein bisschen schlauer \u2014 das ist das Ziel!",
        "Wissen macht das Leben bunter und reicher.",

        // --- April (91-120) ---
        "Ein offener Geist ist der Anfang allen Wissens.",
        "Deine Neugierde ist dein bester Lehrer.",
        "Wissen rostet nicht \u2014 im Gegenteil!",
        "Fragen sind die Antworten der Klugen.",
        "Jeden Tag eine neue Chance, etwas zu entdecken.",
        "Das Wissen von heute ist die Innovation von morgen.",
        "Lernst du noch oder weißt du schon?",
        "Wer denkt, gewinnt \u2014 das gilt auch beim Quiz!",
        "Bildung ist nicht das Füllen eines Eimers, sondern das Entzünden eines Feuers.",
        "Dein nächstes Lieblingsthema wartet auf dich!",
        "Wissen ist wie eine Reise \u2014 der Weg ist das Ziel.",
        "Heute neu gelernt, morgen schon angewendet!",
        "Die wichtigste Investition ist die in den eigenen Kopf.",
        "Jedes Quiz ist ein kleines Abenteuer!",
        "Wissen verdoppelt sich, wenn man es weitergibt.",
        "Sei der Mensch, der immer eine Antwort kennt!",
        "Dein Wissensdurst ist dein Motor.",
        "Lernen öffnet Horizonte, die vorher unsichtbar waren.",
        "Wer neugierig ist, wird nie gelangweilt sein.",
        "Die beste Zeit zum Lernen ist jetzt \u2014 immer jetzt!",
        "Wissen gibt dir die Freiheit, eigene Entscheidungen zu treffen.",
        "Mach dein Gehirn zum stärksten Muskel!",
        "Jede Antwort macht dich ein Stück weiser.",
        "Lernen ist der Schlüssel zu jeder verschlossenen Tür.",
        "Dein Wissen ist einzigartig \u2014 so wie du!",
        "Wer viel weiß, hat viel zu erzählen.",
        "Heute ist Quiztag \u2014 mach das Beste draus!",
        "Wissen ist die beste Verteidigung gegen Langeweile.",
        "Neues Wissen, neue Perspektiven, neue Möglichkeiten!",
        "Dein Kopf ist der großartigste Speicher der Welt.",

        // --- Mai (121-151) ---
        "Lernen hört nie auf \u2014 und das ist wunderbar!",
        "Wissen ist die Währung der Zukunft.",
        "Jeder kluge Gedanke begann mit einer Frage.",
        "Dein Wissensnetzwerk wächst mit jedem Quiz.",
        "Die Welt ist voller Wunder \u2014 entdecke sie!",
        "Wer lernt, lebt doppelt.",
        "Wissen macht dich nicht nur klüger, sondern auch interessanter.",
        "Heute ein Quizheld, morgen ein Wissensgenie!",
        "Die besten Gespräche beginnen mit: Wusstest du schon...?",
        "Jedes neue Wort ist ein neues Werkzeug.",
        "Wissen ist die Brücke zwischen Gestern und Morgen.",
        "Dein Gehirn ist hungrig \u2014 füttere es mit Wissen!",
        "Lernen ist die schönste Form der Selbstverbesserung.",
        "Wer fragt, führt \u2014 auch sich selbst!",
        "Jedes Quiz ist ein Training für den Geist.",
        "Wissen verändert nicht die Welt \u2014 aber die, die es haben.",
        "Stell dir vor, was du morgen alles wissen wirst!",
        "Die Neugier ist die Mutter aller Erfindungen.",
        "Wissen kennt keine Altersgrenzen.",
        "Ein kluger Kopf ist das beste Kapital.",
        "Lerne mit Freude \u2014 es bleibt besser hängen!",
        "Dein Wissensschatz wächst mit jedem Tag.",
        "Die Antwort liegt oft näher als du denkst.",
        "Wissen ist portabel \u2014 nimm es überallhin mit!",
        "Heute gelernt, für immer gewusst.",
        "Dein Verstand ist bereit \u2014 bist du es auch?",
        "Wissen teilen heisst Freude teilen.",
        "Jede Frage bringt dich dem Verständnis näher.",
        "Der Weg zum Experten beginnt mit dem ersten Quiz.",
        "Wissen ist die Flamme, die nie erlischt.",
        "Mach dir die Welt zum Klassenzimmer!",

        // --- Juni (152-181) ---
        "Sommer und Lernen? Passt perfekt zusammen!",
        "Wissen ist die beste Sonnencreme für den Geist.",
        "Jeder Sonnenstrahl bringt eine neue Erkenntnis.",
        "Entspannt lernen \u2014 das geht am besten mit einem Quiz!",
        "Die längsten Tage sind perfekt für neue Entdeckungen.",
        "Wissen ist erfrischend wie ein kühles Getränk.",
        "Dein Gehirn braucht keinen Urlaub vom Lernen!",
        "Nutze die langen Abende für kurze Quizrunden.",
        "Wissen sammeln ist wie Muscheln suchen am Strand.",
        "Jede Jahreszeit hat ihre eigenen Lektionen.",
        "Lerne heute, glänze morgen!",
        "Wissen ist der Schatten, der dich nie verlässt.",
        "Dein Gehirn ist der beste Reisebegleiter.",
        "Neue Fragen, neue Antworten, neues Glück!",
        "Wissen ist die Landkarte deines Lebens.",
        "Jeden Tag ein Stückchen weiser werden.",
        "Die besten Entdeckungen macht man zufällig \u2014 beim Quizzen!",
        "Wissen gibt dir Flügel \u2014 auch ohne Flugzeug.",
        "Lerne spielerisch \u2014 es funktioniert am besten!",
        "Dein Wissensgarten braucht tägliche Pflege.",
        "Wer lernt, erntet \u2014 früher oder später.",
        "Wissen ist der beste Eisbrecher auf jeder Party.",
        "Heute mutig fragen, morgen klug antworten.",
        "Dein nächster Wissens-Durchbruch ist näher als du denkst!",
        "Lernen macht den Unterschied zwischen Träumen und Tun.",
        "Wissen ist die Zutat, die jedem Gespräch Würze gibt.",
        "Sei stolz auf jede richtige Antwort!",
        "Die Welt belohnt die Wissbegierigen.",
        "Heute ist der beste Tag, um anzufangen.",
        "Wissen ist wie Honig \u2014 süß und wertvoll!",

        // --- Juli (182-212) ---
        "Mitten im Sommer, mitten im Lernen!",
        "Wissen kühlt den Kopf und wärmt das Herz.",
        "Jeder Tag ist eine neue Seite im Buch des Wissens.",
        "Dein Gehirn ist das beste Freibad \u2014 tauch ein!",
        "Wissen ist der Kompass, der nie die Richtung verliert.",
        "Lernen unter freiem Himmel \u2014 warum nicht?",
        "Jede Antwort ist ein kleiner Applaus für dein Gehirn.",
        "Wissen macht Sommer noch schöner.",
        "Die besten Ideen kommen in entspannten Momenten.",
        "Quiz am Pool? Warum nicht!",
        "Wissen ist wie Eis \u2014 am besten täglich genießen.",
        "Dein Kopf kennt keine Sommerpause.",
        "Lernen ist die schönste Art, Zeit zu verbringen.",
        "Jeder Tag bringt 24 Stunden voller Möglichkeiten.",
        "Wissen ist der Anker in stürmischen Zeiten.",
        "Sei der Held deiner eigenen Wissensgeschichte!",
        "Lernen macht nicht müde \u2014 es macht wach!",
        "Dein Wissensbaum trägt jeden Tag neue Früchte.",
        "Die beste Investition: Zeit fürs Lernen.",
        "Wissen ist der Diamant, den niemand stehlen kann.",
        "Heute gelernt, morgen angewendet, übermorgen gemeistert!",
        "Dein Gehirn ist ein Wunderwerk \u2014 fordere es heraus!",
        "Wissen verbindet Herz und Verstand.",
        "Jede neue Erkenntnis ist ein Geschenk an dich selbst.",
        "Lernen ist der Weg, Staunen das Ziel.",
        "Wissen kennt keine Grenzen \u2014 genau wie dein Potenzial!",
        "Sei ein Entdecker \u2014 jeden einzelnen Tag!",
        "Die klügsten Köpfe sind die neugierigsten.",
        "Wissen ist die Melodie deines Verstandes.",
        "Heute quizzen, morgen glänzen!",
        "Dein Wissenshunger ist deine Stärke.",

        // --- August (213-243) ---
        "Der Sommer geht, das Wissen bleibt!",
        "Jeder Abend ist eine Chance für ein Quiz.",
        "Wissen ist das Licht am Ende des Tunnels.",
        "Dein Gehirn ist bereit für neue Abenteuer!",
        "Lernen ist keine Last \u2014 es ist ein Privileg.",
        "Die besten Geschichten beginnen mit Wissen.",
        "Wer lernt, hat immer etwas zu erzählen.",
        "Dein Wissensrucksack wird nie zu schwer.",
        "Jede Frage ist ein Schlüssel zu einer neuen Welt.",
        "Wissen macht glücklich \u2014 probier es aus!",
        "Die Welt braucht neugierige Köpfe wie dich!",
        "Lernen ist der beste Weg, sich selbst zu überraschen.",
        "Wissen ist wie ein guter Freund \u2014 immer da, wenn du es brauchst.",
        "Heute ein Quiz, morgen ein Gespräch, das beeindruckt.",
        "Dein Verstand wächst mit jeder Herausforderung.",
        "Wissen ist die Wurzel allen Fortschritts.",
        "Mach Wissen zu deiner täglichen Gewohnheit!",
        "Jede richtige Antwort stärkt dein Selbstvertrauen.",
        "Lernen öffnet Türen \u2014 eine nach der anderen.",
        "Wissen ist der beste Begleiter auf Reisen.",
        "Dein nächstes Aha-Erlebnis wartet im nächsten Quiz!",
        "Die Welt ist ein Buch \u2014 lies jeden Tag eine Seite.",
        "Wissen ist die Kraft, die von innen kommt.",
        "Sei hungrig nach Wissen \u2014 nie satt!",
        "Jeder Tag bietet 86.400 Sekunden zum Lernen.",
        "Wissen ist die Sprache, die alle verstehen.",
        "Dein Kopf ist voller Potenzial \u2014 entfalte es!",
        "Lernen ist der Soundtrack deines Lebens.",
        "Wissen macht stark \u2014 innerlich und äußerlich.",
        "Die besten Quizzer sind die neugierigsten Menschen.",
        "Heute ist dein Tag \u2014 lerne etwas Großartiges!",

        // --- September (244-273) ---
        "Der Herbst des Wissens trägt die reichsten Früchte.",
        "Neue Jahreszeit, neue Lernchancen!",
        "Wissen ist wie buntes Herbstlaub \u2014 vielfaeltig und schoen.",
        "Dein Gehirn blüht auch im Herbst!",
        "Lernen ist die beste Erntedank-Tradition.",
        "Jeder kühle Abend ist perfekt für ein Quiz.",
        "Wissen wärmt von innen \u2014 besser als jeder Tee!",
        "Der Herbst erinnert uns: Veränderung ist Wachstum.",
        "Dein Wissensbaum verliert nie seine Blätter.",
        "Lernen in der Kuschelzeit \u2014 gibt es etwas Besseres?",
        "Wissen ist der goldene Oktober deines Geistes.",
        "Jede Frage ist ein Samenkorn für zukünftige Erkenntnis.",
        "Die besten Ideen reifen wie guter Wein.",
        "Dein Kopf kennt keine Jahreszeiten \u2014 er lernt immer!",
        "Wissen macht den Unterschied zwischen Sehen und Verstehen.",
        "Herbstzeit ist Lesezeit \u2014 und Quizzeit!",
        "Jede Antwort ist ein Blatt mehr an deinem Wissensbaum.",
        "Lernen ist die schönste Herbstbeschaeftigung.",
        "Wissen färbt dein Leben in bunten Farben.",
        "Der kluge Kopf bereitet sich im Herbst auf den Winter vor.",
        "Dein Wissensvorrat kennt kein Verfallsdatum.",
        "Heute lernen, morgen ernten, übermorgen teilen!",
        "Wissen ist die wärmste Decke für kühle Tage.",
        "Jedes Quiz ist ein Spaziergang durch die Welt des Wissens.",
        "Sei wie der Herbst \u2014 lass los, was du nicht brauchst, behalte was zählt!",
        "Wissen ist die Ernte deiner Neugier.",
        "Dein Gehirn ist der beste Heizkörper \u2014 halte es warm mit Wissen!",
        "Lernen macht jeden Tag zum goldenen Oktober.",
        "Die besten Erkenntnisse kommen in stillen Momenten.",
        "Wissen ist das Licht, das den Herbstnebel durchbricht.",

        // --- Oktober (274-304) ---
        "Oktober \u2014 der Monat der großen Fragen!",
        "Wissen gruselt sich nie \u2014 auch nicht an Halloween.",
        "Jede Frage ist ein kleines Rätsel zum Lösen.",
        "Dein Gehirn feiert jeden Tag Halloween \u2014 es liebt Überraschungen!",
        "Wissen ist der Zauber, den jeder lernen kann.",
        "Lernen ist wie Kürbisschnitzen \u2014 am Ende leuchtet es!",
        "Die dunkleren Tage sind perfekt zum Wissensammeln.",
        "Jede Antwort vertreibt ein Stückchen Unwissenheit.",
        "Wissen ist das Licht deiner inneren Laterne.",
        "Sei mutig \u2014 auch bei schwierigen Fragen!",
        "Dein Wissensschatz wird nie von Gespenstern gestohlen.",
        "Lernen ist magisch \u2014 und du bist der Zauberer!",
        "Wissen macht aus jedem Abend einen Filmabend im Kopf.",
        "Jede Frage ist ein Türöffner zu neuen Welten.",
        "Oktober lehrt uns: Auch in der Dunkelheit steckt Schönheit.",
        "Dein Gehirn ist der beste Gruselfilm-Regisseur \u2014 voller Überraschungen!",
        "Wissen ist süß \u2014 ganz ohne Kalorien!",
        "Heute ein Quiz, morgen eine neue Fähigkeit.",
        "Die besten Geschichten schreibt das Wissen.",
        "Jeder Tag ist ein unbeschriebenes Kapitel \u2014 füll es mit Wissen!",
        "Wissen vertreibt die Angst vor dem Unbekannten.",
        "Dein Verstand ist stärker als jeder Geist!",
        "Lernen ist die Taschenlampe im Dunkeln.",
        "Wissen gibt dir Superkräfte \u2014 unsichtbar aber mächtig!",
        "Sei neugierig wie ein Kind, weise wie ein Erwachsener.",
        "Jede Erkenntnis ist ein Schritt näher am Ziel.",
        "Wissen ist die Maske, die nie verrutscht.",
        "Dein Quiz-Abenteuer beginnt mit einem Klick!",
        "Die kürzeren Tage machen das Lernen gemütlicher.",
        "Wissen ist wie Kerzenlicht \u2014 es wärmt und erleuchtet.",
        "Heute mutig quizzen \u2014 keine Angst vor falschen Antworten!",

        // --- November (305-334) ---
        "November \u2014 Zeit für tiefe Gedanken und kluges Wissen.",
        "Wissen ist die beste Gesellschaft an langen Abenden.",
        "Jeder Regentropfen bringt eine neue Idee.",
        "Dein Gehirn blüht auch ohne Sonnenschein!",
        "Lernen ist der wärmste Pullover für den Geist.",
        "Wissen macht graue Tage bunt.",
        "Die stillen Monate sind perfekt zum Nachdenken.",
        "Jede Frage ist ein Fenster in eine andere Welt.",
        "Wissen ist die Heizung deines Verstandes.",
        "Dein Wissensfeuer brennt auch im November!",
        "Lernen ist wie heisse Schokolade \u2014 wärmt und macht glücklich.",
        "Die besten Erkenntnisse kommen an regnerischen Tagen.",
        "Wissen ist der Regenschirm für schwierige Zeiten.",
        "Jeder Tag hat genug Licht zum Lernen.",
        "Dein Gehirn kennt keinen Winterschlaf.",
        "Wissen ist das Feuer, das nie ausgeht.",
        "Nutze die Gemütlichkeit zum Wissenaufbau!",
        "Jede Antwort ist ein Stern am Novemberhimmel.",
        "Lernen verbindet die Herzen und die Köpfe.",
        "Wissen ist dankbar \u2014 es bleibt bei dir!",
        "Die Natur ruht, dein Geist darf weiterwachsen.",
        "Jedes Quiz ist ein kleines Glück im Alltag.",
        "Wissen ist der Leuchtturm in der Dunkelheit.",
        "Dein Verstand ist wie ein Kamin \u2014 je mehr du reinlegst, desto wärmer wird es.",
        "Lernen macht den November zum Wissens-November!",
        "Die besten Bücher und Quizze warten auf dich.",
        "Wissen ist die Brücke über jedes Tief.",
        "Sei dankbar für jeden neuen Gedanken.",
        "Dein Wissensweg führt immer vorwärts.",
        "November-Weisheit: Ruhe ist die Schwester des Lernens.",

        // --- Dezember (335-365) ---
        "Dezember \u2014 das Jahr in Wissen zusammenfassen!",
        "Wissen ist das schönste Geschenk unter dem Baum.",
        "Jeder Tag im Advent bringt neue Erkenntnisse.",
        "Dein Gehirn feiert mit \u2014 gib ihm ein Wissensgeschenk!",
        "Lernen im Kerzenschein \u2014 magisch!",
        "Wissen ist der Stern, dem die Weisen folgen.",
        "Die festliche Zeit ist perfekt für kluge Gespräche.",
        "Jede Frage ist eine Kerze am Adventskranz des Wissens.",
        "Wissen glänzt heller als jede Weihnachtskugel.",
        "Dein Wissens-Adventskalender hat 365 Türchen!",
        "Lernen ist das Geschenk, das du dir selbst machst.",
        "Die besten Vorsätze beginnen mit Wissen.",
        "Wissen ist wie Schnee \u2014 es verwandelt die Welt.",
        "Jeder letzte Tag im Jahr ist der erste Tag neuen Wissens.",
        "Dein Gehirn braucht keine Winterpause!",
        "Wissen macht die Feiertage noch schöner.",
        "Die gemütlichste Zeit ist die beste Lernzeit.",
        "Jede Antwort ist ein Geschenk an dich selbst.",
        "Wissen ist die Melodie der Weihnachtszeit.",
        "Dein Jahresrückblick: So viel gelernt, so viel gewachsen!",
        "Lernen kennt keine Feiertage \u2014 und das ist gut so!",
        "Wissen ist der beste Silvester-Vorsatz.",
        "Die letzten Tage des Jahres gehören den besten Fragen.",
        "Dein Wissenstagebuch ist voller Einträge \u2014 sei stolz!",
        "Wissen verbindet alte und neue Jahre.",
        "Jedes Ende ist ein neuer Anfang \u2014 auch beim Lernen.",
        "Dein Gehirn hat dieses Jahr Großartiges geleistet!",
        "Wissen ist die Rakete ins neue Jahr.",
        "Auf ein neues Jahr voller Fragen, Antworten und Wissen!",
        "Silvester-Weisheit: Das Beste liegt immer noch vor dir.",
        "365 Tage Wissen \u2014 und morgen geht es weiter!"
    )
}
